var todayquote = new Array (1232);
todayquote [101] = ["JANUARY 1" , "I AM A MIRACLE" , "The central fact of our lives today is the absolute certainty that our Creator has entered into our hearts and lives in a way that is indeed miraculous. He has commenced to accomplish those things for us which we could never do for ourselves." , "ALCOHOLICS ANONYMOUS, p. 25" , "This truly is a fact in my life today, and a real miracle. I always believed in God, but could never put that belief meaningfully into my life. Today, because of Alcoholics Anonymous, I now trust and rely on God, as I understand Him; I am sober today because of that! Learning to trust and rely on God was something I never could have done alone. I now believe in miracles because I am one!"];
todayquote [102] = ["JANUARY 2" , "FIRST, THE FOUNDATION" , "Is sobriety all that we can expect of a spiritual awakening? No, sobriety is only a bare beginning." , "AS BILL SEES IT, p. 8" , "Practicing the A.A. program is like building a house. First I had to pour a big, thick concrete slab on which to erect the house; that, to me, was the equivalent of stopping drinking. But it's pretty uncomfortable living on a concrete slab, unprotected and exposed to the heat, cold, wind and rain. So I built a room on the slab by starting to practice the program. The first room was rickety because I wasn't used to the work. But, as time passed, as I practiced the program, I learned to build better rooms. The more I practiced, and the more I built, the more comfortable, and happy, was the home I now have to live in."];
todayquote [103] = ["JANUARY 3","POWERLESS","We admitted we were powerless over alcohol - that our lives had become unmanageable.","TWELVE STEPS AND TWELVE TRADITIONS, p. 21","It is no coincidence that the very first Step mentions powerlessness: An admission of personal powerlessness over alcohol is a cornerstone of the foundation of recovery. I've learned that I do not have the power and control I once thought I had. I am powerless over what people think of me. I am powerless over having just missed the bus. I am powerless over how other people work (or don't work) the Steps. But I'm also learned I am <i>not</i> powerless over some things. I am <i>not</i> powerless over my attitudes. I am <i>not</i> powerless over negativity. I am <i>not</i> powerless over assuming responsibility for my own recovery. I have the power to exert an influence on myself, my loved ones, and the world in which I live."]
todayquote [104] = ["JANUARY 4" , "BEGIN WHERE YOU ARE" , "We feel that elimination of our drinking is but a beginning. A much more important demonstration of our principles lies before us in our respective homes, occupations and affairs." , "ALCOHOLICS ANONYMOUS, p.19" , "It's usually pretty easy for me to be pleasant to the people in an A.A. setting. While I'm working to stay sober, I'm celebrating with my fellow A.A.s our common release from the hell of drinking. It's often not so hard to spread glad tidings to my old and new friends in the program. <br> At home or work, though, it can be a different story. It is in situations arising in both of those areas that the little day-to-day frustrations are most evident, and where it can be tough to smile or reach out with a kind word or be an attentive ear. It's outside of the A.A. rooms that I face the real test of the effectiveness of my walk through A.A.'s Twelve Steps."]
todayquote [105] = ["JANUARY 5" , "TOTAL ACCEPTANCE" , "He cannot picture life without alcohol. Someday he will be unable to imagine life either with alcohol or without it. Then he will know loneliness such as few do. He will be at the jumping-off place. He will wish for the end." , "ALCOHOLICS ANONYMOUS, p. 152" , `Only an alcoholic can understand the exact meaning of a statement like this one. The double standard that held me captive as an active alcoholic also filled me with terror and confusion: "If I don't get a drink I'm going to die" competed with "If I continue drinking it's going to kill me." Both compulsive thoughts pushed me ever closer to the bottom. That bottom produced a <i>total</i> acceptance of my alcoholism - with no reservations whatsoever - and one that was absolutely essential for my recovery. It was a dilemma unlike anything I had ever faced, but as I found out later on, a necessary one if I was to succeed in this program.`]
todayquote [106] = ["JANUARY 6" , "THE VICTORY OF SURRENDER" , "We perceive that only through utter defeat are we able to take our first steps toward liberation and strength. Our admissions of personal powerlessness finally turn out to be firm bedrock upon which happy and purposeful lives can be built." , "TWELVE STEPS AND TWELVE TRADITIONS, p. 21" , "When alcohol influenced every facet of my life, when bottles became the symbol of all my self-indulgence and permissiveness, when I came to realize that, by myself, I could do nothing to overcome the power of alcohol, I realized I had no recourse except surrender. In surrender I found victory - victory over my selfish self-indulgence, victory over my stubborn resistance to life as it was given to me. When I stopped fighting anybody or anything, I started on the path to sobriety, serenity and peace."]
todayquote [107] = ["JANUARY 7" , "AT THE TURNING POINT" , "Half measures availed us nothing. We stood at the turning point. We asked His protection and care with complete abandon." , "ALCOHOLICS ANONYMOUS, p. 59" , "Every day I stand at turning points. My thoughts and actions can propel me toward growth or turn me down the road to old habits and booze. Sometimes turning points are beginnings, as when I decide to start praising, instead of condemning someone. Or when I begin to ask for help instead of going it alone. At other times turning points are endings, such as when I see clearly the need to stop festering resentments or crippling self-seeking. Many shortcomings tempt me daily; therefore I also have daily opportunities to become aware of them. In one form or another, many of my character defects appear daily: self-condemnation, anger, running away, being prideful, wanting to get even, or acting out of grandiosity. <br> Attempting half measures to eliminate these defects merely paralyzes my efforts to change. It is only when I ask God for help, with complete abandon, that I become willing - and able - to change."]
todayquote [108] = ["JANUARY 8" , "DO I HAVE A CHOICE?" , "The fact is that most alcoholics, for reasons yet obscure, have lost the power of choice in drink. Our so-called will power becomes practically nonexistent." , "ALCOHOLICS ANONYMOUS, p.24" , `My powerlessness over alcohol does not cease when I quit drinking. In sobriety I still have no choice - I can't drink. <br> The choice I <i>do have</i> is to pick up and use the "kit of spiritual tools" (<i>ALCOHOLICS ANONYMOUS</i>, p. 25). When I do that, my Higher Power relieves me of my lack of choice - and keeps me sober <i>one more day</i>. If I could choose <i>not to</i> pick up a drink today, where then would be my need for A.A. or a Higher Power? `]
todayquote [109] = ["JANUARY 9" , "AN ACT OF PROVIDENCE" , "It is truly awful to admit that, glass in hand, we have warped our minds into such an obsession for destructive drinking that only an act of Providence can remove it from us." , "TWELVE STEPS AND TWELVE TRADITIONS, p.21" , "My act of Providence, (a manifestation of divine care and direction), came as I experienced the total bankruptcy of active alcoholism - everything meaningful in my life was gone. I telephoned Alcoholics Anonymous and, from that instant, my life has never been the same. When I reflect on that very special moment, I know that God was working in my life long before I was able to acknowledge and accept spiritual concepts. The glass was put down through this one act of Providence and my journey into sobriety began. My life continues to unfold with divine care and direction. Step One, in which I admitted I was powerless over alcohol, that my life had become unmanageable, takes on more meaning for me - one day at a time - in the life-saving, life-giving Fellowship of Alcoholics Anonymous."]
todayquote [110] = ["JANUARY 10" , "UNITED WE STAND" , "We learned that we had to fully concede to our innermost selves that we were alcoholics. This is the first step in recovery. The delusion that we are like other people, or presently may be, has to be smashed." , "ALCOHOLICS ANONYMOUS, p.30" , "I came to Alcoholics Anonymous because I was no longer able to control my drinking. It was either my wife's complaining about my drinking, or maybe the sheriff forced me to go to A.A. meetings, or perhaps I knew, deep down inside, that I couldn't drink like others, but I was unwilling to admit it because the alternative terrified me. Alcoholics Anonymous is a fellowship of men and women united against a common, fatal disease. Each one of our lives is linked to every other, much like the survivors on a life raft at sea. If we all work together, <i>we can get safely to shore</i>."]
todayquote [111] = ["JANUARY 11" , "THE 100% STEP" , "Only Step One, where we made the 100 percent admission we were powerless over alcohol, can be practiced with absolute perfection." , "TWELVE STEPS AND TWELVE TRADITIONS, p. 68" , "Long before I was able to attain sobriety in A.A., I knew without a doubt that alcohol was killing me, yet even with this knowledge, I was unable to stop drinking. So, when faced with Step One, I found it easy to admit that I lacked the power not to drink. But was my life unmanageable? Never! Five months after coming into A.A., I was drinking again and wondered why.<br> Later on, back in A.A. and smarting from my wounds, I learned that Step One is the only step that can be taken 100%. And that the only way to take it 100% is to take 100% of the Step. That was many twenty-four hours ago and I haven't had to take Step One again."]
todayquote [112] = ["JANUARY 12" , "ACCEPTING OUR PRESENT CIRCUMSTANCES" , "Our very first problem is to accept our present circumstances as they are, ourselves as we are, and the people around us as they are. This is to adopt a realistic humility without which no genuine advance can even begin. Again and again, we shall need to return to that unflattering point of departure. This is an exercise in acceptance that we can profitably practice every day in our lives." , "AS BILL SEES IT, p. 44" , "When I am having a difficult time accepting people, places or events, I turn to this passage and it relieves me of many an underlying fear regarding others, or situations life presents me. The thought allows me to be human and not perfect, and to regain my peace of mind."]   
todayquote [113] = ["JANUARY 13" , "IT DOESN'T HAPPEN OVERNIGHT" , "We are not cured of alcoholism. What we really have is a daily reprieve contingent on the maintenance of our spiritual condition." , "ALCOHOLICS ANONYMOUS, p. 85" , `The most common alcoholic fantasy seems to be: "If I just don't drink, everything will be all right." Once the fog cleared for me, I saw - for the first time - the mess my life had become. I had family, work, financial and legal problems; I was hung up on old religious ideas; there were sides of my character to which I was inclined to stay blind because they easily could have convinced me that I was hopeless and pushed me toward escape again. The Big Book guided me in resolving <i>all</i> of my problems. But it didn't happen overnight - and certainly not automatically - with no effort on my part. I need to always recognize God's mercy and blessings that shine through any problem I have to face.`]   
todayquote [114] = ["JANUARY 14" , "NO REGRETS" , "We shall not regret the past nor wish to shut the door on it." , "ALCOHOLICS ANONYMOUS, p.83" , "Once I became sober, I began to see how wasteful my life has been and I experienced overwhelming guilt and feelings of regret. The program's Fourth and Fifth Steps assisted me enormously in healing these troubling regrets. I learned that my self-centeredness and dishonesty stemmed largely from my drinking and that I drank because I was an alcoholic. Now I see how even my most distasteful past experiences can turn to gold because, as a sober alcoholic, I can share them to help my fellow alcoholics, particularly newcomers. Sober for several years in A.A., I no longer regret the past; I am simply grateful to be conscious of God's love and the help I can give to others in the Fellowship."]
todayquote [115] = ["JANUARY 15" , "AN UNSUSPECTED INNER RESOURCE" , "With few exceptions our members find that they have tapped an unsuspected inner resource which they presently identify with their own conception of a Power greater than themselves." , "ALCOHOLICS ANONYMOUS, pp. 567-68" , `From my first days in A.A., as I struggled for sobriety, I found hope in these words from our founders. I often pondered the phrase "they have tapped an unsuspected inner resource." How, I asked myself, can I find the Power within myself, since I am so powerless? In time, as the founders promised, it came to me: I have always had the choice between goodness and evil, between unselfishness and selfishness, between serenity and fear. That Power greater than myself is an original gift that I did not recognize until I achieved daily sobriety through living A.A.'s Twelve Steps.`]
todayquote [116] = ["JANUARY 16" , "HITTING BOTTOM" , "Why all this insistence that every A.A. must hit bottom first? The answer is that few people will sincerely try to practice the A.A. program unless they have hit bottom. For practicing A.A.'s remaining eleven Steps means the adoption of attitudes and actions that almost no alcoholic who is still drinking can dream of taking." , "Twelve Steps and Twelve Traditions, p.24" , "Hitting bottom opened my mind and I became willing to try something different. What I tried was A.A. My new life in the Fellowship was a little like learning to ride a bike for the first time: A.A. became my training wheels <i>and</i> my supporting hand. It's not that I wanted the help so much at the time; I simply did not want to hurt like that again. My desire to avoid hitting bottom again was more powerful than my desire to drink. In the beginning that was what kept me sober. But after a while I found myself working the Steps to the best of my ability. I soon realized that my attitudes and actions were changing - if ever so slightly. One Day at a Time, I became comfortable with myself, and others, and my hurting started to heal. Thank God for the training wheels and supporting hand that I choose to call Alcoholics Anonymous."]
todayquote [117] = ["JANUARY 17" , "HAPPINESS COMES QUIETLY" , "The trouble with us alcoholics was this: we demanded that the world give us happiness and peace of mind in just the particular order we wanted to get it -- by the alcohol route. And we weren't successful. But when we take time to find out some of the spiritual laws, and familiarize ourselves with them, and put them into practice, then we do get happiness and peace of mind. ... There seem to be some rules that we always have to follow, but happiness and peace of mind are always here, open and free to everyone." , "DR. BOB AND THE GOOD OLDTIMERS, p. 308" , `The simplicity of the A.A. program teaches me that happiness isn't something I can "demand". It comes to me quietly, while I serve others. In offering my hand to the newcomer or to someone who has relapsed, I find that my own sobriety has been recharged with indescribable gratitude and happiness.`]
todayquote [118] = ["JANUARY 18" , "WOULD A DRINK HELP?" , "By going back in our own drinking histories, we could show that years before we realized it we were out of control, that our drinking even then was no mere habit, that it was indeed the beginning of a fatal progression." , "TWELVE STEPS AND TWELVE TRADITIONS, p. 23" , "When I was still drinking, I couldn't respond to any of life's situations the way other, more healthy people could. The smallest incident triggered a state of mind that believed I had to have a drink to numb my feelings. But the numbing did not improve the situation, so I sought further escape in the bottle. Today I must be aware of my alcoholism. I cannot afford to believe that I have gained control of my drinking - or again I will think I have gained control of my life. Such a feeling of control is fatal to my recovery."]
todayquote [119] = ["JANUARY 19" , "ROUND-THE-CLOCK FAITH" , "Faith has to work twenty-four hours a day in and through us, or we perish." , "ALCOHOLICS ANONYMOUS, p. 16" , "The essence of my spirituality, and my sobriety, rests on a round-the-clock faith in a Higher Power. I need to remember and rely on the God of my understanding as I pursue all of my daily activities. How comforting for me is the concept that God works in and through people. As I pause in my day, do I recall specific concrete examples of God's presence? Am I amazed and uplifted by the number of times this power is evident? I am overwhelmed with gratitude for God's presence in my life of recovery. Without this omnipotent force in my every activity, I would again fall into the depths of my disease - and death."]
todayquote [120] = ["JANUARY 20" , "WE PAUSE ... AND ASK" , "As we go through the day we pause, when agitated or doubtful, and ask for the right thought or action." , "ALCOHOLICS ANONYMOUS, p.87" , "Today I humbly ask my Higher Power for the grace to find the space between my impulse and my action; to let flow a cooling breeze when I would respond with heat; to interrupt fierceness with gentle peace, to accept the moment which allows judgment to become discernment; to defer to silence when my tongue would rush to attack or defend.<br> I promise to watch for every opportunity to turn toward my Higher Power for guidance. I know where this power is: it resides within me, as clear as a mountain brook, hidden in the hills - it is the unsuspected Inner Resource. <br> I thank my Higher Power for this world of light and truth I see when I allow it to direct my vision. I trust it today and hope it trusts me to make all effort to find the right thought or action today."]
todayquote [121] = ["JANUARY 21" , "SERVING MY BROTHER" , "The member talks to the newcomer not in a spirit of power but in a spirit of humility and weakness." , "ALCOHOLICS ANONYMOUS COMES OF AGE, p. 279" , "As the days pass in A.A., I ask God to guide my thoughts and the words that I speak. In this labor of continuous participation in the Fellowship, I have numerous opportunities to speak. So I frequently ask God to help me watch over my thoughts and my words, that they may be the true and proper reflections of our program; to focus my aspirations once again to seek His guidance; to help me be truly kind and loving, helpful and healing, yet always full of humility, and free from any trace of arrogance. <br> Today I may well have to deal with disagreeable attitudes or utterances - the typical stock-in-trade attitude of the still-suffering alcoholic. If this should happen, I will take a moment to center myself in God, so that I will be able to respond from a perspective of composure, strength and sensibility."]
todayquote [122] = ["JANUARY 22" , `"LET'S KEEP IT SIMPLE"` , `A few hours later I took my leave of Dr. Bob. The wonderful, old, broad smile was on his face as he said almost jokingly, "Remember, Bill, let's not louse this thing up. Let's keep it simple!" I turned away, unable to say a word. That was the last time I ever saw him.` , "ALCOHOLICS ANONYMOUS COMES OF AGE, p. 214" , `After years of sobriety I occasionally ask myself "Can it be this simple?" Then, at meetings, I see former cynics and skeptics who have walked the A.A. path out of hell by packaging their lives, without alcohol, into twenty-four hour segments, during which they practice a few principles to the best of their individual abilities. And then I know again that, while it isn't always easy, if I keep it simple, it works.`]
todayquote [123] = ["JANUARY 23" , "HAVING FUN YET?" , "... We aren't a glum lot. If newcomers could see no joy or fun in our existence, they wouldn't want it. We absolutely insist on enjoying life. We try not to indulge in cynicism over the state of the nations, nor do we carry the world's troubles on our shoulders." , "ALCOHOLICS ANONYMOUS, p. 132" , "When my own house is in order, I find the different parts of my life are more manageable. Stripped from the guilt and remorse that cloaked my drinking  years, I am free to assume my proper role in the universe, but this position requires maintenance. If I should stop and ask myself, <i>Am I having fun yet?</i> If I find answering that question difficult or painful, perhaps I'm taking myself too seriously - and finding it difficult to admit that I've strayed from my practice of working the program to keep my house in order. I think the pain I experience is one way my Higher Power has to get my attention, coaxing me to take stock of my performance. The slight time and effort it takes to work the program - s spot-check inventory, for example, or the making of amends, whatever is appropriate - are well worth the effort."]
todayquote [124] = ["JANUARY 24" , "GETTING INVOLVED" , 'There is action and more action. "Faith without works is dead." ... To be helpful is our only aim.' , "ALCOHOLICS ANONYMOUS p. 88-89" , 'I understand that service is a vital part of recovery, but I often wonder, "What can I do?" Simply start with what I have today! I look around to see where there is a need. Are the ashtrays full? Do I have hands and feet to empty them? Suddenly I`m involved! The best speaker may make the worst coffee; the member who is best with newcomers may be unable to read; the one wiling to clean up may make a mess of the bank account - yet every one of these people and jobs is essential to an active group. The miracle of service is this: when I use what I have, I find there is more available to me than I realized before.']
todayquote [125] = ["JANUARY 25" , "WHAT WE NEED - EACH OTHER" , '... A.A. is really saying to every serious drinker, "You are a member if YOU say so." ... Nobody can keep you out.' , "Twelve Steps and Twelve Traditions, p. 139" , 'For years, whenever I reflected on "Tradition Three" ("The only requirement for A.A. membership is a desire to stop drinking") I thought it valuable only to newcomers. It was their guarantee that no one could bar them from A.A. Today I feel enduring gratitude for the spiritual development the Third Tradition has brought me. I don`t seek out people obviously different from myself. Tradition Three, concentrating on the one way I am similar to others, brought me to know and help every kind of alcoholic, just as they have helped me. Charlotte, the atheist, showed me higher standards of ethics and honor; Clay, of another race, taught me patience; Winslow, who is gay, led me by example into true compassion; Young Megan says that seeing me at meetings, sober thirty years, keeps her coming back. Tradition Three insured that we would get what we need - each other. ']
todayquote [126] = ["JANUARY 26" , "" , "" , "" , ""]
todayquote [127] = ["JANUARY 27" , "" , "" , "" , ""]
todayquote [128] = ["JANUARY 28" , "" , "" , "" , ""]
todayquote [129] = ["JANUARY 29" , "" , "" , "" , ""]
todayquote [130] = ["JANUARY 30" , "" , "" , "" , ""]

theDate = new Date();
var day = ("0" + theDate.getDate()).slice(-2)
var month = theDate.getMonth();
var d = month + 1 + "" + day;
var textdate = (theDate.getMonth() + 1) + ' / ' + theDate.getDate();

function dateAssign(d){
document.getElementById("debug").innerHTML = d;
document.getElementById("date").innerHTML = todayquote[d][0];
document.getElementById("title").innerHTML = todayquote[d][1];
document.getElementById("quote").innerHTML = todayquote[d][2];
document.getElementById("attribution").innerHTML = todayquote[d][3];
document.getElementById("commentary").innerHTML = todayquote[d][4];
}

// dateAssign(d);
dateAssign(120);

// 101 beginning, d - 1 previous, d + 1 next, 1231 end
